- name: Create a folder inside jenkins
  community.general.jenkins_job:
    config: "{{ lookup('template', 'templates/pipeline.xml') }}"
    name: test
    token: "11910207df2a2e8b3e1ed155f6cff9cf09"
    url: http://172.31.7.26:8080
    user: admin
  loop:
    - {repoName: "cart", componentName: "cart"}


