- name: Create a folder inside jenkins
  community.general.jenkins_job:
    config: "{{ lookup('template', 'templates/pipeline.xml') }}"
    name: test
    password: admin123
    url: http://172.31.7.26:8080
    user: admin
  loop:
    - {repoName: "cart", componentName: "cart"}


